# Generated by Django 5.0 on 2025-03-21 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Justificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('hora_actual', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
