# Generated by Django 5.0 on 2025-03-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_justificaciones_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificaciones',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
