# Generated by Django 5.0 on 2025-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_justificaciones_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificaciones',
            name='grado',
            field=models.CharField(default='', max_length=20),
        ),
    ]
